local CL_Donar = {
	name              	= "Donar",
	description         = "Attack VTOL",
	objectName        	= "CL_Donar.s3o",
	script				= "Vehicle.lua",
	corpse				= "CL_Donar_X",
	explodeAs          	= "mechexplode",
	category 			= "vtol air notbeacon",
	noChaseCategory		= "beacon air",
	sightDistance       = 800,
	radarDistance      	= 1500,
		activateWhenBuilt   = true,
		onoffable           = true,
	maxDamage           = 5300,
	mass                = 2500,
	footprintX			= 2,
	footprintZ 			= 2,
	collisionVolumeType = "box",
	collisionVolumeScales = "25 25 35",
	collisionVolumeOffsets = "0 1 0",
	collisionVolumeTest = 1,
	buildCostEnergy     = 20,
	buildCostMetal      = 7110,
	buildTime           = 0,
	canFly				= true,
		cruiseAlt		= 200,
		bankScale		= "1",
		hoverAttack		= true,
		steeringMode	= "1",
		defaultmissiontype  = "VTOL_standby",
		maneuverleashlength = "1000",
	canMove				= true,
		movementClass   = "VTOL",
		maxVelocity		= 8.1, --150kph/30
		maxReverseVelocity= 4,
		acceleration    = 0.8,
		brakeRate       = 8.1,
		turnRate 		= 810,
	
	canAttack 			= true,
		--Makes unit use weapon from /weapons folder
		weapons 		= {	
			[1] = {
				name	= "CLPL",
				OnlyTargetCategory = "notbeacon",
				mainDir = "0 0 1",
				maxAngleDif = 90,
			},
			[2] = {
				name	= "LRM5",
				OnlyTargetCategory = "notbeacon",
				WeaponSlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 90,
			},
			[3] = {
				name	= "LRM5",
				OnlyTargetCategory = "notbeacon",
				WeaponSlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 90,
			},
		},
	customparams = {
		hasturnbutton	= "1",
		helptext		= "Armament: 1 x Large Pulse Laser, 2 x ATM-6 - Armor: 3 tons",
		flagcaprate		= "0",
		flagdefendrate	= "0",
		heatlimit		= "24",
		unittype		= "vehicle",
    },
}

return lowerkeys({ ["CL_Donar"] = CL_Donar })