local CL_Donar = {
	name              	= "Donar",
	description         = "Attack VTOL",
	objectName        	= "CL_Donar.s3o",
	iconType			= "aero",
	script				= "Vehicle.lua",
	corpse				= "CL_Donar_X",
	explodeAs          	= "mechexplode",
	category 			= "vtol air notbeacon",
	noChaseCategory		= "beacon air vtol",
	sightDistance       = 800,
	radarDistance      	= 1500,
		activateWhenBuilt   = true,
		onoffable           = true,
	maxDamage           = 5300,
	mass                = 2500,
	footprintX			= 2,
	footprintZ 			= 2,
	collisionVolumeType = "box",
	collisionVolumeScales = "25 25 35",
	collisionVolumeOffsets = "0 1 0",
	collisionVolumeTest = 1,
	buildCostEnergy     = 20,
	buildCostMetal      = 9500,
	buildTime           = 0,
	canFly				= true,
		cruiseAlt		= 250,
		hoverAttack		= true,
		airStrafe		= false,
	canMove				= true,
		movementClass   = "VTOL",
		airHoverFactor	= -0.0001,
		maxVelocity		= 8.6,
		acceleration	= 0.2,
		brakeRate 		= 1600,
		turnRate 		= 800,
		verticalSpeed	= 1,
	canAttack 			= true,
		--Makes unit use weapon from /weapons folder
		weapons 		= {	
			[1] = {
				name	= "CERLBL",
				OnlyTargetCategory = "notbeacon",
				mainDir = "0 0 1",
				maxAngleDif = 90,
			},
			[2] = {
				name	= "SSRM2",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 90,
			},
			[3] = {
				name	= "SSRM2",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 90,
			},
		},
	customparams = {
		hasturnbutton	= "1",
		helptext		= "Armament: 1 x Large Pulse Laser, 2 x SSRM-2- Armor: 3 tons",
		flagcaprate		= "0",
		flagdefendrate	= "0",
		heatlimit		= "24",
		unittype		= "vehicle",
    },
}

return lowerkeys({ ["CL_Donar"] = CL_Donar })