--  Custom Options Definition Table format

--  NOTES:
--  - using an enumerated table lets you specify the options order

--
--  These keywords must be lowercase for LuaParser to read them.
--
--  key:      the string used in the script.txt
--  name:     the displayed name
--  desc:     the description (could be used as a tooltip)
--  type:     the option type
--  def:      the default value;
--  min:      minimum value for number options
--  max:      maximum value for number options
--  step:     quantization step, aligned to the def value
--  maxlen:   the maximum string length for string options
--  items:    array of item strings for list options
--  scope:    "all", "player", "team", "allyteam"      <<< not supported yet >>>


--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
local options = {
	----------------------------------------------------------------------------
	{
		key		= '1start',
		name	= 'Start Conditions',
		desc	= 'Sets options regarding winning conditions and resources',
		type	= 'section',
	},
	----------------------------------------------------------------------------
	{
		key		= "skip_briefing",
		name 	= "Skip Startup Briefing",
		desc 	= "Skips the startup briefing",
		type	= "bool",
		def		= false,
		section	= '1start',
	},
	{
		key		= "locktoprofile",
		name 	= "Lock To Profile Starts (Choose Before / In Game)",
		desc 	= "Snaps all starting positions to those defined in the map profile. Also enforces the number of starts as the maximum number of teams.",
		type	= "bool",
		def		= true,
		section	= '1start',
	},
	{
		key		= "start_tickets",
		name	= "Tickets",
		desc	= "Starting Tickets",
		type	= "number",
		def		= 200,
		min		= 100,
		max		= 1000,
		step	= 10,
		section = '1start',
	},
	{
		key		= "startcbills",
		name	= "Starting C-Bills",
		desc	= "Sets the amount of C-Bills players start with at the beginning of the game.",
		type	= "number",
		def		= 25000,
		min		= 15000,
		max		= 100000,
		step	= 100,
		section	= "1start",
	},
	{
		key		= "starttonnage",
		name	= "Starting Tonnage",
		desc	= "Sets the base tonnage of dropships (each upgrades adds to this)",
		type	= "number",
		def		= 150,
		min		= 20,
		max		= 1000,
		step	= 10,
		section	= "1start",
	},
	{
		key		= "startsalvage",
		name	= "Starting Salvage",
		desc	= "Sets the amount of Salvage players start with at the beginning of the game.",
		type	= "number",
		def		= 100,
		min		= 0,
		max		= 1000,
		step	= 10,
		section	= "1start",                    
	},
	----------------------------------------------------------------------------
	{
		key		= '2income',
		name	= 'Income & Costs',
		desc	= 'Sets options regarding income and costs',
		type	= 'section',
	},
	----------------------------------------------------------------------------
	{
		key		= "income",
		name	= "Beacon Income",
		desc	= "How many CBills per beacon per second?",
		type	= "number",
		def		= 50,
		min		= 1,
		max		= 1000,
		step	= 1,
		section	= '2income',
	},
	{
		key		= "capincome",
		name	= "Point Capping Income",
		desc	= "How many CBills per capped point?",
		type	= "number",
		def		= 2000,
		min		= 0,
		max		= 50000,
		step	= 100,
		section	= '2income',
	},
	{
		key		= "income_damage",
		name	= "Damage Income (Multiplier)",
		desc	= "How many CBills per HP of damage?",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= '2income',
	},
	{
		key		= "insurance",
		name	= "Insurance (Multiplier)",
		desc	= "How many CBills returned to owner when a mech dies",
		type	= "number",
		def		= 0.2,
		min		= 0.01,
		max		= 1.0,
		step	= 0.01,
		section	= '2income',
	},
	{
		key		= "sell",
		name	= "Selling Price (Multiplier)",
		desc	= "What proportion of CBills returned to owner when a mech is sold",
		type	= "number",
		def		= 0.75,
		min		= 0.05,
		max		= 1.0,
		step	= 0.05,
		section	= '2income',
	},
	{
		key		= "pricemult",
		name	= "Mech Price Multiplier",
		desc	= "Multiplier for CBill cost of mechs",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= '2income',
	},
	{
		key		= "outpostmult",
		name	= "Outpost Price Multiplier",
		desc	= "Multiplier for CBill cost of Outposts",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 2.0,
		step	= 0.1,
		section	= '2income',
	},
	{
		key		= "tonnagemult",
		name	= "Tonnage Multiplier",
		desc	= "Multiplier for the available tonnage per dropship",
		type	= "number",
		def		= 1.0,
		min		= 1.0,
		max		= 2.5,
		step	= 0.1,
		section	= '2income',
	},
	{
		key		= "salvageperpile",
		name	= "Salvage Per Pile (multiplier)",
		desc	= "Multiplier for the amount of salvage per pile",
		type	= "number",
		def		= 1,
		min		= 1,
		max		= 100,
		step	= 1,
		section	= '2income',
	},
	{
		key		= "salvagepertick",
		name	= "Salvage Per Tick (multiplier)",
		desc	= "Multiplier for the amount of salvage per tick generated by a stocked salvage yard",
		type	= "number",
		def		= 1,
		min		= 1,
		max		= 100,
		step	= 1,
		section	= '2income',
	},
	{
		key		= "modcostmult",
		name	= "Mod costs (multiplier)",
		desc	= "Multiplier for the salvage cost of mods",
		type	= "number",
		def		= 1,
		min		= 1,
		max		= 100,
		step	= 1,
		section	= '2income',
	},
	----------------------------------------------------------------------------
	{
		key		= '3game',
		name	= 'Gameplay Options',
		desc	= 'Sets gameplay options',
		type	= 'section',
	},
	----------------------------------------------------------------------------
	
	{
		key		= "vehicle_delay",
		name 	= "Vehicle Delay",
		desc 	= "Minimum delay between vehicle spawns",
		type	= "number",
		def    	= 45,
		min		= 5,
		max		= 300,
		step	= 5,
		section	= '3game',
	},
	{
		key		= "beaconpoints",
		name	= "Default Beacon Points",
		desc	= "Default number of outpost points per beacon (where not map-specified)",
		type	= "number",
		def		= 3,
		min		= 3,
		max		= 12,
		step	= 3,
		section	= '3game',
	},
	{
		key		= "perkeffect",
		name	= "Perk Effect %",
		desc	= "% To increase/decrease by when perking attributes",
		type	= "number",
		def		= 5,
		min		= 1,
		max		= 100,
		step	= 1,
		section	= "3game",
	},
	{
		key  = "fowstyle",
		name = "Fog of War Style",
		desc = "Choose whether unseen terrain uses the darker Unexplored appearance or the lighter Explored appearance.",
		type = "list",
		def  = "explored",
		items = {
			{
				key  = "unexplored",
				name = "Unexplored",
				desc = "Terrain starts dark and becomes lighter after it has been explored.",
			},
			{
				key  = "explored",
				name = "Explored",
				desc = "All unseen terrain uses the lighter Explored appearance from the start.",
			},
		},
	},
	{
		key		= "ai_difficulty",
		name	= "SpamBot AI difficulty level",
		desc	= "Sets the difficulty level of the SpamBot.",
		type	= "list",
		def		= "1",
		items = {
			{
				key		= "1",
				name	= "Regular",
				desc	= "Random unit selection. No resource cheating."
			},
			{
				key		= "2",
				name	= "Banker",
				desc	= "Random unit selection. C-Bill cheating."
			},
		}
	},
	{
		key  = "texmod_botbuddy",
		name = "Bot Buddy Paint Schemes",
		desc = "Apply each human team's selected paint scheme to that team's Bot Buddy units where matching texmod textures exist.",
		type = "bool",
		def  = false,
	},
	----------------------------------------------------------------------------
	{
		key    = '4devtools',
		name   = 'Developer Sandbox',
		desc   = 'Sets options for tweaking balance',
		type   = 'section',
	},
	----------------------------------------------------------------------------
	{
		key		= "damagemult",
		name	= "Test Damage Multiplier",
		desc	= "Developer tool",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= "devtools",
	},
	{
		key		= "vehicledamagemult",
		name	= "Test Vehicle only Damage Multiplier",
		desc	= "Developer tool",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= "devtools",
	},
	{
		key		= "rangemult",
		name	= "Test Weapon Range Multiplier",
		desc	= "Developer tool",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= "devtools",
	},
	{
		key		= "ammomult",
		name	= "Test Weapon Ammo Multiplier",
		desc	= "Developer tool",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= "devtools",
	},
	{
		key		= "coolrate",
		name	= "Test Coolrate Multiplier",
		desc	= "Developer tool",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= "devtools",
	},
	{
		key		= "heatlimit",
		name	= "Test heatlimit Multiplier",
		desc	= "Developer tool",
		type	= "number",
		def		= 1.0,
		min		= 0.1,
		max		= 10.0,
		step	= 0.1,
		section	= "devtools",
	},
	{
		key = "speed",
		name = "Test Speed Multipliers",
		desc = "Developer tool",
		type = "number",
		def = 0.75,
		min = 0.1,
		max = 100,
		section = "devtools",
	},
	{
		key = "torso",
		name = "Test Torso Rotation Multipliers",
		desc = "Developer tool",
		type = "number",
		def = 1,
		min = 0.1,
		max = 5.0,
		step = 0.1,
		section = "devtools",
	},
	{
		key = "turn",
		name = "Test Turnrate Multipliers",
		desc = "Developer tool",
		type = "number",
		def = 1,
		min = 0.1,
		max = 5.0,
		step = 0.1,
		section = "devtools",
	},
	{
		key = "mechsight",
		name = "Test Mech LOS Radius",
		desc = "Developer tool",
		type = "number",
		def = 400, --250,
		min = 10,
		max = 500,
		step = 50,
		section = "devtools",
	},
	{
		key = "sectorangle",
		name = "Test Mech Sector Angle",
		desc = "Developer tool",
		type = "number",
		def = 2,
		min = 0.1,
		max = 5,
		step = 0.1,
		section = "devtools",
	},
	{
		key = "sectorrange",
		name = "Test Mech Sector Range",
		desc = "Developer tool",
		type = "number",
		def = 1000,
		min = 500,
		max = 2000,
		step = 50,
		section = "devtools",
	},
	{
		key = "radar",
		name = "Test Radar Radius Multiplier",
		desc = "Developer tool",
		type = "number",
		def = 1, --0.75,
		min = 0.1,
		max = 1.5,
		step = 0.1,
		section = "devtools",
	},
}
return options
