local featureDefs = {
  debris1 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris1.s3o",
    reclaimable        = false,
  },
  debris2 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris2.s3o",
    reclaimable        = false,
  },
  debris3 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris3.s3o",
    reclaimable        = false,
  },
  debris4 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris4.s3o",
    reclaimable        = false,
  },
  debris5 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris5.s3o",
    reclaimable        = false,
  },
  debris6 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris7.s3o",
    reclaimable        = false,
  },
  debris7 = {
    blocking           = false,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/debris7.s3o",
    reclaimable        = false,
  },
  sign1 = {
    blocking           = false,
    damage             = 800,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/sign1.s3o",
    reclaimable        = false,
  },
  pipes1 = {
    blocking           = false,
    damage             = 800,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/pipes1.s3o",
    reclaimable        = false,
  },
  pipes2 = {
    blocking           = false,
    damage             = 800,
    description        = "Derelict Structure",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 0,
    object             = "ruin/pipes2.s3o",
    reclaimable        = false,
  },
}
return featureDefs