weaponDef = {
	name                    = "Extended Range Small Beam Laser",
	weaponType              = "BeamLaser",
	beamLaser				= true,
	beamLaser				= 1,
--	beamWeapon				= true,
--	largeBeamLaser			= true,
	renderType				= 0,
	lineOfSight				= true,
	explosionGenerator    	= "custom:Laser_Small",
	soundHit              	= [[GEN_Beam_Explode1]],
	soundStart           	= [[SBL_Fire]],
	burnblow				= true, 	--Bullets explode at range limit.
	collideFriendly			= true,
	noSelfDamage            = true,
	turret                  = true,
	range                   = 500,
	accuracy                = 10,
	tollerance				= 100,
	areaOfEffect            = 5,
	weaponVelocity          = 2000,
	weaponTimer				= 0.8,
	reloadtime              = 2.5,
	size 					= 0.05,
	laserFlareSize			= 0.1,
	thickness				= 0.75,
	coreThickness			= 0.1,
	beamDecay          		= 1,
	beamTime           		= 0.5,
	beamTTL           		= 0.5,
	minIntensity			= 1,
	rgbcolor				= "1.0 0.4 0.4",
	intensity				= 0.75,
	damage = {
		default = 125, --30 DPS
		beacons = 0,
		light = 125,
		medium = 112.5, --90%
		heavy = 100, --80%
		assault = 87.5, --70%
		vehicle = 187.5, --150%
		vtol = 187.5, --150%
	},
	customparams = {
		heatgenerated		= "5",--2/sec
		cegflare			= "LASER_MUZZLEFLASH",
    },
}

return lowerkeys({ ERSBL = weaponDef })