weaponDef = {
	name                    = "TAG Laser",
	weaponType              = "BeamLaser",
	beamLaser				= true,
	beamBurst				= true,
	renderType				= 0,
	lineOfSight				= true,
	explosionGenerator    	= "custom:Nothing",
	--soundHit              	= [[GEN_Beam_Explode1]],
	soundStart           	= [[TAG_Fire]],
	soundTrigger			= 1,
	burnblow				= true, 	--Bullets explode at range limit.
	collideFriendly			= true,
	noSelfDamage            = true,
	turret                  = true,
	canAttackGround			= false,
	range                   = 1500,
	accuracy                = 50,
	tolerance				= 100,
	areaOfEffect            = 5,
	weaponVelocity          = 2000,
	weaponTimer				= 0.8,
	reloadtime              = 0.1,
	size 					= 0.05,
	laserFlareSize			= 0.1,
	thickness				= 0.75,
	coreThickness			= 0.1,
	beamDecay          		= 1,
	beamTime           		= 0.5,
	beamTTL           		= 0.5,
	burst					= 10,
	burstrate				= 0.01,
	minIntensity			= 1,
	rgbcolor				= "1.0 0.4 0.4",
	intensity				= 0.25,
	damage = {
		default = 0.0000001, 
	},
	customparams = {
		heatgenerated		= "0",--2/sec
		cegflare			= "SMALLLASER_MUZZLEFLASH",
		flareonshot			= true,
		weaponclass			= "energy",
		tag					= "1",
    },
}

return lowerkeys({ TAG = weaponDef })