 -- C3 Pieces
local emitterbase1, emitter1, geo1, emitterbase2, emitter2, geo2 = piece ("emitterbase1", "emitter1", "geo1", "emitterbase2", "emitter2", "geo2")
local door1a, door1b, door2a, door2b, gendoor1, gendoor2, generator1, generator2 = piece ("door1a", "door1b", "door2a", "door2b", "gendoor1", "gendoor2", "generator1", "generator2")
local foot1, foot2, foot3, foot4 = piece ("foot1", "foot2", "foot3", "foot4")

-- C3 unpack anim
function Deploy()
	PlaySound("Whir")
	Move(legs[1], x_axis, 12, CRATE_SPEED * 10)
	Move(legs[1], y_axis, -2, CRATE_SPEED * 3)
	Move(legs[2], x_axis, 12, CRATE_SPEED * 10)
	Move(legs[2], y_axis, -2, CRATE_SPEED * 3)
	Move(legs[3], x_axis, -12, CRATE_SPEED * 10)
	Move(legs[3], y_axis, -2, CRATE_SPEED * 3)
	Move(legs[4], x_axis, -12, CRATE_SPEED * 10)
	Move(legs[4], y_axis, -2, CRATE_SPEED * 3)
	WaitForMove(legs[1], x_axis)
	WaitForMove(legs[2], x_axis)
	WaitForMove(legs[3], x_axis)
	WaitForMove(legs[4], x_axis)
	Turn(foot1, z_axis, math.rad(-90), CRATE_SPEED * 2)
	Turn(foot2, z_axis, math.rad(-90), CRATE_SPEED * 2)
	Turn(foot3, z_axis, math.rad(90), CRATE_SPEED * 2)
	Turn(foot4, z_axis, math.rad(90), CRATE_SPEED * 2)
	PlaySound("Thunk")
	Sleep(1000)
	Move(door1a, z_axis, 10, CRATE_SPEED * 20)
	WaitForMove(door1a, z_axis)
	Move(door1b, z_axis, 15, CRATE_SPEED * 20)
	WaitForMove(door1b, z_axis)
	Move(emitterbase1, y_axis, 15, CRATE_SPEED * 10)
	WaitForMove(emitterbase1, y_axis)
	Move(emitter1, y_axis, 11.5, CRATE_SPEED * 10)
	WaitForMove(emitter1, y_axis)
	Move(gendoor1, z_axis, -12, CRATE_SPEED * 8)
	WaitForMove(gendoor1, z_axis)
	Move(generator1, x_axis, 13, CRATE_SPEED * 8)
	WaitForMove(generator1, x_axis)
	Spin(geo1, y_axis, math.rad(100), math.rad(15))
	Sleep(1000)
	GG.LanceControl(teamID, unitID, true)
	Spring.UnitScript.SetUnitValue(COB.ACTIVATION, 1)
end

-- C3 upgrade anim
function Upgrade2()
	Move(door2a, z_axis, -10, CRATE_SPEED * 20)
	WaitForMove(door2a, z_axis)
	Move(door2b, z_axis, -15, CRATE_SPEED * 20)
	WaitForMove(door2b, z_axis)
	Move(emitterbase2, y_axis, 15, CRATE_SPEED * 10)
	WaitForMove(emitterbase2, y_axis)
	Move(emitter2, y_axis, 11.5, CRATE_SPEED * 10)
	WaitForMove(emitter2, y_axis)
	Move(gendoor2, z_axis, 12, CRATE_SPEED * 8)
	WaitForMove(gendoor2, z_axis)
	Move(generator2, x_axis, -13, CRATE_SPEED * 8)
	WaitForMove(generator2, x_axis)
	Spin(geo2, y_axis, math.rad(100), math.rad(15))
	Sleep(1000)
end