-- AirCon pieces
local tower_mid, tower_top, ladder, antennadoor1, radardoor1, radardoor2 = piece ("tower_mid", "tower_top", "ladder", "antennadoor1", "radardoor1", "radardoor2")
local radar_mount, radar_spin, radar_arm1, radar_arm2, antennabase, antenna1_1, antenna1_2, antenna2_1, antenna2_2 = piece ("radar_mount", "radar_spin", "radar_arm1", "radar_arm2", "antennabase", "antenna1_1", "antenna1_2", "antenna2_1", "antenna2_2")

local rad = math.rad

function Deploy()
	Move(tower_mid, y_axis, 7, CRATE_SPEED * 8)
	PlaySound("HeavyLift")
	WaitForMove(tower_mid, y_axis)
	Move(tower_top, y_axis, 24, CRATE_SPEED * 12)
	Turn(legs[1], z_axis, rad(90), CRATE_SPEED * 2)
	Move(legs[1], x_axis, -11, CRATE_SPEED * 8)
	Move(legs[1], y_axis, 1, CRATE_SPEED * 8)
	Turn(legs[2], x_axis, rad(90), CRATE_SPEED * 2)
	Move(legs[2], z_axis, 11, CRATE_SPEED * 8)
	Move(legs[2], y_axis, 1, CRATE_SPEED * 8)
	Turn(legs[3], z_axis, rad(-90), CRATE_SPEED * 2)
	Move(legs[3], x_axis, 11, CRATE_SPEED * 8)
	Move(legs[3], y_axis, 1, CRATE_SPEED * 8)
	Turn(legs[4], x_axis, rad(-90), CRATE_SPEED * 2)
	Move(legs[4], z_axis, -11, CRATE_SPEED * 8)
	Move(legs[4], y_axis, 1, CRATE_SPEED * 8)
	PlaySound("Hydraulic_Click")
	WaitForMove(tower_top, y_axis)
	Move(radardoor1, z_axis, 8, CRATE_SPEED * 10)
	Move(radardoor2, z_axis, -8, CRATE_SPEED * 10)
	Move(antennadoor1, z_axis, -8, CRATE_SPEED * 14)
	PlaySound("ElectricDoor")
	Sleep(50)
	PlaySound("ElectricDoor")
	WaitForMove(radardoor1, z_axis)
	Move(radar_mount, y_axis, 35, CRATE_SPEED * 18)
	Move(antennabase, y_axis, 5, CRATE_SPEED * 12)
	Move(antenna2_1, y_axis, 10, CRATE_SPEED * 12)
	PlaySound("Uplink_Whir")
	Sleep(100)
	PlaySound("Whir_Small")
	Move(antenna2_2, y_axis, 6, CRATE_SPEED * 8)
	Move(antenna1_1, y_axis, 10, CRATE_SPEED * 10)
	WaitForMove(radar_mount, y_axis)
	PlaySound("Whir_Small")
	Turn(radar_arm1, x_axis, rad(-90), CRATE_SPEED * 1)
	Turn(radar_arm2, x_axis, rad(90), CRATE_SPEED * 1)
	PlaySound("Hydraulic_Click")
	Sleep(50)
	Spin(radar_spin, y_axis, rad(40), rad(10))
	Sleep(100)
	Move(ladder, y_axis, -26, CRATE_SPEED * 32)
	PlaySound("Gear_Small")
	WaitForMove(antenna1_1, y_axis)
	Move(antenna1_2, y_axis, 11, CRATE_SPEED * 12)
	PlaySound("Whir_Small")
	Spring.UnitScript.SetUnitValue(COB.ACTIVATION, 1)
end