local featureDefs = {
  salvage = {
    blocking           = false,
    damage             = 5400,
    description        = "Salvage",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 2000,
    object             = "salvage.s3o",
    reclaimable        = true,
  },
  salvage_1 = {
    blocking           = false,
    damage             = 5400,
    description        = "Salvage",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 2000,
    object             = "salvage_1.s3o",
    reclaimable        = true,
  },
   salvage_2 = { -- ugh need to sort out OO defs
    blocking           = false,
    damage             = 5400,
    description        = "Salvage",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 2000,
    object             = "salvage_2.s3o",
    reclaimable        = true,
  },
    salvage_3 = {
    blocking           = false,
    damage             = 5400,
    description        = "Salvage",
    footprintX         = 1,
    footprintZ         = 1,
    metal              = 2000,
    object             = "salvage_3.s3o",
    reclaimable        = true,
  },
}
return featureDefs