local IS_Sparrowhawk = {
	name              	= "Sparrowhawk",
	description         = "Light Interceptor ASF",
	objectName        	= "IS_Sparrowhawk.s3o",
	iconType			= "aero",
	script				= "Vehicle.lua",
	explodeAs          	= "mechexplode",
	category 			= "aero air notbeacon",
	noChaseCategory		= "beacon ground",
	sightDistance       = 1200,
	radarDistance      	= 1500,
		activateWhenBuilt   = true,
		onoffable           = true,
	maxDamage           = 350,
	mass                = 2000,
	footprintX			= 2,
	footprintZ 			= 2,
	collisionVolumeType = "box",
	collisionVolumeScales = "25 25 35",
	collisionVolumeOffsets = "0 1 0",
	collisionVolumeTest = 1,
	buildCostEnergy     = 20,
	buildCostMetal      = 4500,
	buildTime           = 0,
	canFly				= true,
		cruiseAlt		= 300,
		canLoopbackAttack = true,
		factoryHeadingTakeoff = false,
		turnRadius		= 1000,
		maxAcc			= 0.18,
		maxBank			= 0.0007,
		maxPitch		= 0.0007,
		maxAileron		= 0.0045,
		maxElevator		= 0.004,
		maxRudder		= 0.002,
		wingAngle		= 0.1,
		wingDrag		= 0.07,
	canMove				= true,
		movementClass   = "AERO",
		--maxVelocity		= 90,
		myGravity		= 0.8,
	
	canAttack 			= true,
		--Makes unit use weapon from /weapons folder
		weapons 		= {	
			[1] = {
				name	= "MBL",
				OnlyTargetCategory = "notbeacon",
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
			[2] = {
				name	= "MBL",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
			[3] = {
				name	= "ERSBL",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
			[4] = {
				name	= "ERSBL",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
		},
	customparams = {
		hasturnbutton	= "1",
		helptext		= "Armament: 2 x Medium Pulse Laser, 2 x ER Small Beam Laser - Armor: 2 tons",
		flagcaprate		= "0",
		flagdefendrate	= "0",
		heatlimit		= "15",
		unittype		= "vehicle",
    },
}

return lowerkeys({ ["IS_Sparrowhawk"] = IS_Sparrowhawk })