local IS_Sparrowhawk = {
	name              	= "Sparrowhawk",
	description         = "Light Interceptor ASF",
	objectName        	= "IS_Sparrowhawk.s3o",
	iconType			= "aero",
	script				= "Vehicle.lua",
	explodeAs          	= "mechexplode",
	category 			= "air notbeacon",
	noChaseCategory		= "beacon",
	sightDistance       = 1200,
	radarDistance      	= 1500,
		activateWhenBuilt   = true,
		onoffable           = true,
	maxDamage           = 3500,
	mass                = 2000,
	footprintX			= 2,
	footprintZ 			= 2,
	collisionVolumeType = "box",
	collisionVolumeScales = "25 25 35",
	collisionVolumeOffsets = "0 1 0",
	collisionVolumeTest = 1,
	buildCostEnergy     = 20,
	buildCostMetal      = 4500,
	buildTime           = 0,
	canFly				= true,
		cruiseAlt		= 300,
		bankScale		= "1",
		steeringMode	= "1",
		defaultmissiontype  = "VTOL_standby",
		maneuverLeashLength = "2000",
		factoryHeadingTakeoff = false,
	canMove				= true,
		movementClass   = "AERO",
		maxVelocity		= 18.6, --280kph/15
		maxReverseVelocity= 4,
		acceleration    = 0.8,
		brakeRate       = 8.1,
		turnRate 		= 800,
		myGravity		= 0.5,
	
	canAttack 			= true,
		--Makes unit use weapon from /weapons folder
		weapons 		= {	
			[1] = {
				name	= "CMPL",
				OnlyTargetCategory = "notbeacon",
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
			[2] = {
				name	= "CMPL",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
			[3] = {
				name	= "CERSBL",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
			[4] = {
				name	= "CERSBL",
				OnlyTargetCategory = "notbeacon",
				SlaveTo = 1,
				mainDir = "0 0 1",
				maxAngleDif = 35,
			},
		},
	customparams = {
		hasturnbutton	= "1",
		helptext		= "Armament: 2 x Medium Pulse Laser, 2 x ER Small Beam Laser - Armor: 2 tons",
		flagcaprate		= "0",
		flagdefendrate	= "0",
		heatlimit		= "15",
		unittype		= "vehicle",
    },
}

return lowerkeys({ ["IS_Sparrowhawk"] = IS_Sparrowhawk })