local featureDefs = {
  small_glass_building_1 = {
    blocking           = true,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 2,
    footprintZ         = 2,
    metal              = 200,
    object             = "ruin/small_glass_building_1.s3o",
    reclaimable        = true,
  },
  small_glass_building_2 = {
    blocking           = true,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 2,
    footprintZ         = 2,
    metal              = 200,
    object             = "ruin/small_glass_building_2.s3o",
    reclaimable        = true,
  },
  small_glass_building_3 = {
    blocking           = true,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 2,
    footprintZ         = 2,
    metal              = 200,
    object             = "ruin/small_glass_building_3.s3o",
    reclaimable        = true,
  },
  small_glass_building_4 = {
    blocking           = true,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 2,
    footprintZ         = 2,
    metal              = 200,
    object             = "ruin/small_glass_building_4.s3o",
    reclaimable        = true,
  },
  small_glass_building_5 = {
    blocking           = true,
    damage             = 1000,
    description        = "Derelict Structure",
    footprintX         = 2,
    footprintZ         = 2,
    metal              = 200,
    object             = "ruin/small_glass_building_5.s3o",
    reclaimable        = true,
  },
}
return featureDefs